2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Configure stats pid to 31210
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Loading settings from /home/labicquette/.config/wandb/settings
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Loading settings from /home/labicquette/M1/intro-to-nlp-Nantes/projet-nlp-Nantes/wandb/settings
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'legal_eval_ft.py', 'program_abspath': '/home/labicquette/M1/intro-to-nlp-Nantes/projet-nlp-Nantes/legal_eval_ft.py', 'program': '/home/labicquette/M1/intro-to-nlp-Nantes/projet-nlp-Nantes/legal_eval_ft.py'}
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:_log_setup():526] Logging user logs to /home/labicquette/M1/intro-to-nlp-Nantes/projet-nlp-Nantes/wandb/run-20240312_185914-x97a4hl9/logs/debug.log
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:_log_setup():527] Logging internal logs to /home/labicquette/M1/intro-to-nlp-Nantes/projet-nlp-Nantes/wandb/run-20240312_185914-x97a4hl9/logs/debug-internal.log
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:init():566] calling init triggers
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:init():616] starting backend
2024-03-12 18:59:14,439 INFO    MainThread:31210 [wandb_init.py:init():620] setting up manager
2024-03-12 18:59:14,440 INFO    MainThread:31210 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-12 18:59:14,441 INFO    MainThread:31210 [wandb_init.py:init():628] backend started and connected
2024-03-12 18:59:14,442 INFO    MainThread:31210 [wandb_init.py:init():720] updated telemetry
2024-03-12 18:59:14,444 INFO    MainThread:31210 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-12 18:59:42,611 INFO    Thread-4 (wrapped_target):31210 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f9f037827d0>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/labicquette/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/labicquette/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f9f037827d0>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/labicquette/.local/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/labicquette/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f9f037827d0>: Failed to resolve 'api.wandb.ai' ([Errno -3] Temporary failure in name resolution)"))
2024-03-12 19:00:00,702 WARNING MainThread:31210 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/labicquette/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
